version: '3.7'

volumes:
  microvik-data:

networks:
  workline-net:
    driver: bridge

services:
# kafka cluster
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - workline-net
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9997:9997
    hostname: kafka
    networks:
      - workline-net
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://${KAFKA_BROKER_IP}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    networks:
      - workline-net
    ports:
      - 8082:8080
    restart: always
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      SPRING_CONFIG_ADDITIONAL-LOCATION: /kafka/config.yml
    volumes:
      - ./config/kafka/config.yml:/kafka/config.yml
    links:
      - kafka
      - zookeeper
# CockroachDB Node
  roach-node:
    container_name: roach-node
    image: cockroachdb/cockroach:latest
    ports:
      - "8083:8080"
      - "26257:26257"
    command: bash -c "cockroach start --insecure --join=roach-node --listen-addr=roach-node:26257 --advertise-addr=roach-node:26257 --max-sql-memory=.25 --cache=.25"
    environment:
      ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD}
    volumes:
      - ./config/cockroachdb/setup_db.sh:/setup_db.sh
      - microvik-data:/cockroach/cockroach-data
    networks:
      - workline-net